### ISSUE TITLE
Update to dor-services 5.x

### ISSUE THREAD

**Issue by atz** [sul-dlss/purl-fetcher#1]
IF necessary.  The main transition is for field names derived from the Solr schema.  It is unclear whether any work is necessary here, mainly because it is unclear how much of `dor-fetcher-service` remains in place.  There are tests that are clearly `dor-fetcher-service` logic, and those features did need to be updated for `dor-fetcher-service`.  They may very well be irrelevant to to `purl-fetcher-app`, in which case they should be *deleted*.  

From the outside it is impossible to reason about what is uniquely `purl-fetcher` about this former branch of `dor-fetcher-service`.

**Comment by atz** [comment]
This is what was required to update the other application: https://github.com/sul-dlss/dor-fetcher-service/pull/36

**Comment by lmcglohon** [comment]
Fixed by https://github.com/sul-dlss/purl-fetcher/pull/5
