### ISSUE TITLE
publish robot needs to create changes file after successful publish

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/purl-fetcher#103]
This is to support https://github.com/sul-dlss/purl-fetcher/issues/66.

Implies that common-accessioning and dor-services-app get the updated dor-services gem

- [x] update `publish_metadata` in dor-services
- [x] release new dor-services
- [x] update common-accessioning for new dor-services
- [x] update dor-services-app for new dor-services
- [x] deploy to dev, stage, prod

**Comment by blalbrit** [comment]
#sul-dlss/dor-services/224

**Comment by drh-stanford** [comment]
See dor-services PR is here: https://github.com/sul-dlss/dor-services/pull/225
