### ISSUE TITLE
port scanner yielding EOFError: bad content body exceptions to honeybadger

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/purl-fetcher#115]
## Backtrace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/48916/faults/30727724)

**Comment by drh-stanford** [comment]
Something is posting to purl-fetcher from `/wp-content/plugins/xml-and-csv-import-in-article-content/upload-process.php"`?

**Comment by drh-stanford** [comment]
We believe that this is a port scan issue. We'd like to disable these bad routes from going to honeybadger.

**Comment by cbeer** [comment]
We've seen this on other projects too; the error seems to happen so far down the stack, I'm not sure we'll be able to squelch this scanner without dropping potentially real errors.
