### ISSUE TITLE
Update runlog job logging for rake find:all

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/purl-fetcher#120]
To reproduce:

```
rake find:all[1] &
sleep 10
rake find:all
```
the second rake will exit without doing or saying anything.

**Comment by mejackreed** [comment]
I think this will also happens if a `find` task gets interuppted and doesn't cleanup  itself in the `RunLog`

**Comment by drh-stanford** [comment]
This also happens on deploy when the listener restarts and tries to kick off the delta run

```
I, [2016-08-16T14:27:09.806134 #2071]  INFO -- : Listening to /purl/recent_changes
I, [2016-08-16T14:27:14.004464 #2320]  INFO -- : Job currently running. No action taken.
I, [2016-08-16T14:27:14.004653 #2320]  INFO -- : Ran 'find:changes[4684]' in 1 seconds
I, [2016-08-16T14:27:14.008291 #2320]  INFO -- : Ran 'find:deletes[4684]' in 1 seconds
```

**Comment by blalbrit** [comment]
Change to write ERROR to log instead of INFO

**Comment by blalbrit** [comment]
Make cleanup happen on a more aggressive schedule (12 hours)
