### ISSUE TITLE
Check in a secrets.yml

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/purl-fetcher#13]
Rather than local devs creating one, just check one in. We can then set it as a `linked_file` in our deploy and set via shared configs.

https://github.com/sul-dlss/earthworks/blob/master/config/deploy.rb#L27

**Comment by drh-stanford** [comment]
This is now in the `shared` folder for the deploys.

See https://github.com/sul-dlss/purl-fetcher/blob/master/config/deploy.rb#L15

For `ci` it's checked in as a `.example` file:

See https://github.com/sul-dlss/purl-fetcher/blob/master/lib/tasks/ci.rake#L42

Not sure what the action item is here now with this previous work. Should we just move the `secrets.yml.example` to `secrets.yml` and remove from `.gitignore`? The capistrano piece is done.

I would argue the same holds for the `solr.yml` file -- the `.example` is not needed -- it can just be checked in.

**Comment by mejackreed** [comment]
> Not sure what the action item is here now with this previous work. Should we just move the secrets.yml.example to secrets.yml and remove from .gitignore? The capistrano piece is done.

Yes this as long as the secrets in the checked in file are different from our deployed ones.
