### ISSUE TITLE
can pages.total_pages be zero on empty results?

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/purl-fetcher#131]
When the `/docs/deletes` or `/docs/changes` API is given a last_modified parameter that yields zero results, the `pages.total_pages` is 0 but the `pages.current_page` is 1. Is that as expected?

Here's an example of the empty result set:

```
{
deletes: [ ],
pages: {
current_page: 1,
next_page: null,
prev_page: null,
total_pages: 0,
per_page: 100,
offset_value: 0,
first_page?: true,
last_page?: true
}
}
```

**Comment by mejackreed** [comment]
This is Kaminari's default behavior. If we want to override it we can, and I get what you are saying.
