### ISSUE TITLE
improve query speed on /docs/changes API

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/purl-fetcher#139]
in production these queries take ~1 min.  would need to set `config.log_level = :debug` to see the specific SQL queries to explain on.

**Comment by mejackreed** [comment]
Can you post some specific queries  that were problematic? I'm getting fast results now.. maybe DB threads were overloaded?

**Comment by drh-stanford** [comment]
Sure. `/docs/changes?first_modified=2016-08-01T22:53:14Z` is taking 38 seconds

```
I, [2016-08-19T15:06:24.398350 #27314]  INFO -- : Completed 200 OK in 38182ms (Views: 446.2ms | ActiveRecord: 37713.8ms)
```

subsequently grabbing page 321 took 8 seconds.

```
I, [2016-08-19T15:07:34.242309 #18346]  INFO -- : Completed 200 OK in 8232ms (Views: 499.9ms | ActiveRecord: 7727.9ms)

```

This may be acceptable performance but I don't know for sure. I created the issue to investigate.

**Comment by mejackreed** [comment]
Here is the expanded log for the 38 second query in prod:

https://gist.github.com/mejackreed/4856fb1cb30ae1fba392e7211a33fcd0

**Comment by drh-stanford** [comment]
Here's the longest SQL query: Purl Load (39086.4ms)  

```sql
SELECT  `purls`.* FROM `purls` WHERE `purls`.`deleted_at` IS NULL AND 
(`purls`.`published_at` BETWEEN '2016-08-01T22:53:14Z' AND '2016-08-22T15:21:08Z')  
ORDER BY published_at LIMIT 100 OFFSET 0
```

**Comment by drh-stanford** [comment]
Here's the EXPLAIN output: 
```
id	select_type	table	type	possible_keys	key	key_len	ref	rows	Extra
1	SIMPLE	purls	index	index_purls_on_deleted_at,index_purls_on_published_at	index_purls_on_published_aNULL	200	Using where
```

**Comment by drh-stanford** [comment]
In production, when querying `/docs/changes?page=7460` it takes ~45 seconds to process that final page. When doing `2016-08-22T00:00:00Z` it takes ~40 seconds, but the final page only takes ~5 seconds.

The explain varies depending on which page you're on -- on the first page it's using the original index not the new one.
```
mysql> explain SELECT  `purls`.* FROM `purls` WHERE `purls`.`deleted_at` IS NULL AND  (`purls`.`published_at` BETWEEN '2016-08-01T22:53:14Z' AND '2016-08-22T15:21:08Z')   ORDER BY published_at LIMIT 100 OFFSET 0;
+----+-------------+-------+-------+--------------------------------------------------------------------------------------------------+-----------------------------+---------+------+------+-------------+
| id | select_type | table | type  | possible_keys                                                                                    | key                         | key_len | ref  | rows | Extra       |
+----+-------------+-------+-------+--------------------------------------------------------------------------------------------------+-----------------------------+---------+------+------+-------------+
|  1 | SIMPLE      | purls | index | index_purls_on_deleted_at,index_purls_on_published_at,index_purls_on_published_at_and_deleted_at | index_purls_on_published_at | 9       | NULL |  400 | Using where |
```

**Comment by drh-stanford** [comment]
The prod purl-fetcher is getting lots ActiveRecord response times in the 5-10 second range which seems plenty fast. But see #95 for why we're not seeing anything much > 10 seconds.

**Comment by drh-stanford** [comment]
mysqld tuning worked in production.
