### ISSUE TITLE
cannot parse some public XML files in production

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/purl-fetcher#140]
so there’s 39 PURLs in production that have data parsing problems. Here’s one — it can’t get the druid out of `//publicObject@id` — see https://purl.stanford.edu/wf048nx0420.xml 

here’s some others (from `log/indexing.log`)

```
cc194nr5321 cw795zs2349 dp217ht0877 dy685nf4395 fj096ht7467 fr073zv0724
fz858hd6588 gq329fs9022 gr137tg0292 jv979fw8535 km097rd5656 ks485yz2876
md225cb2391 mr497sx5638 nd109dt4068 ns433mb7781 pt254ff9966 py409cp8971
rb069xm8239 rf468nq4709 rs788cb1324 tg006fh6427 wf048nx0420 wf977zr5113
```

are these valid PURLs or old bad data?

Ben says:

> These are EEMS objects that are undergoing remediation at the moment (valid PURLs but bad old data)

**Comment by LynnMcRae** [comment]
A document root of \<objectType>? Mercy me these are ancient!  Nice to get them cleaned up.

**Comment by lmcglohon** [comment]
How do we want to handle bad data?

**Comment by LynnMcRae** [comment]
These have been republished so the document root issue (lack of object id) is fixed. Despite their age and EEM-ness, hopefully no other preview issues lurk deeper in the data.

**Comment by LynnMcRae** [comment]
all but druid:cw795zs2349 that is, it won't even display ... that has problems of its own, investigating

**Comment by LynnMcRae** [comment]
druid:cw795zs2349  is now fixed. It had an isMemberOfCollection statement with no druid.

**Comment by lmcglohon** [comment]
We believe that this will not occur again because these were produced by a very old version of publish before it provided objectIds.  Since the old data has been remediated, I am closing this ticket.
