### ISSUE TITLE
duplicates release tags in /docs/changes API response

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/purl-fetcher#152]
For example, `/docs/changes` yields something like this (in stage):

```
{
druid: "druid:bb104kn2363",
latest_change: "2016-08-10T00:17:22Z",
true_targets: [
"SearchWorksPreview"
],
false_targets: [
"Searchworks",
"Searchworks",
"Searchworks",
"Searchworks",
"Searchworks",
"Searchworks",
"Searchworks",
"Searchworks",
"Searchworks"
],
collections: [
"druid:bs646cd8717"
]
},
```

from a public XML file like so:

```
<publicObject id="druid:bb104kn2363" published="2016-08-10T00:17:18Z" publishVersion="dor-services/5.9.0">
<identityMetadata>
...
<release to="Searchworks">false</release>
</identityMetadata>
...
<releaseData>
<release to="Searchworks">false</release>
</releaseData>
</publicObject>
```

release_tags might need a unique index on name+purl_id?

**Comment by LynnMcRae** [comment]
A side note, just to avoid confusion coming from the public.xml itself.  The first <release> tag in identityMetadata should not be there.  It has history and additional data in DOR and is consumed to create the net release status in <releaseData> in the public object. A copy is not mean to land in identityMetadata as well. I thought this was fixed but republish just now did not eliminate it in your sample object. I'll file a ticket.
