### ISSUE TITLE
document operational implications that find:all is not transactional

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/purl-fetcher#154]
while  `find:all` is running, discovery-dispatcher must not contact the `/docs` API, otherwise it will get an incomplete set of PURLs and cannot recover. we rely on the listener and immediate updates to keep the data store transactional

**Comment by eefahy** [comment]
documented in https://github.com/sul-dlss/DevOpsDocs/blob/master/projects/purl-fetcher/operations-concerns.md
