### ISSUE TITLE
Implement singles API

### ISSUE THREAD

**Issue by laneymcg** [sul-dlss/purl-fetcher#167]
This is for items not in collections - object_type = "item" and collections = [ ]

Should look something like:

/singles/:id and provide json output with id, release tags and catkey (if one exists)

**Comment by laneymcg** [comment]
Already done. /purls/:id

**Comment by mejackreed** [comment]
Ok, so I have this working in the Purl API. This is currently the approach:

`/purls?object_type=item&in_collection=false`

I'm not really happy with `in_collection`.. any help on the name? Getting stuck there.

**Comment by drh-stanford** [comment]
`/purls?object_type=item&membership_type=none`? where the latter argument could be `none` or `collection`, for example.

**Comment by laneymcg** [comment]
what about just 
/purls?object_type=item&membership=none 
where the latter argument could be none or collection, for example.
