### ISSUE TITLE
[prod] /purl/pages has undefined method `druid' for nil:NilClass

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/purl-fetcher#173]
## Backtrace

    line 1 of [PROJECT_ROOT]/app/views/v1/purls/_purl.json.jbuilder: _app_views_v__purls__purl_json_jbuilder__1247116328238363603_29279540
    line 1 of [PROJECT_ROOT]/app/views/v1/purls/show.json.jbuilder: _app_views_v__purls_show_json_jbuilder__332075361263831430_70235268738680

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/48916/faults/31113400)

**Comment by mejackreed** [comment]
I think this will/can be resolved with cb815fc in PR #178

**Comment by lmcglohon** [comment]
CLosed with PR #178
