### ISSUE TITLE
If a purl is deleted, the corresponding record in the purl-fetcher database needs to be deleted

### ISSUE THREAD

**Issue by lmcglohon** [sul-dlss/purl-fetcher#175]
When a purl is deleted, as opposed to when the release data field is changed from true to false, the corresponding record in the purl-fetcher database needs to be removed.  For example, the purl for druid zc933cw0607 was deleted because the object was placed in the SDR graveyard. However, when the purl-fetcher API is called for the druid, the druid is returned with a true-target for SearchworksPreview. The purl-fetcher database should include only published purls so the database record should have been deleted. See attached files for the current corresponding argo record display and the result from the purl-fetcher API (purl-fetcher-prod.stanford.edu/purls/zc933cw0607)

![zc933cw0607_argo](https://cloud.githubusercontent.com/assets/3585151/19057016/c72e7baa-8981-11e6-9c4b-ecaaa04fc2c6.png)

![zc933cw0607_purl_fetcher](https://cloud.githubusercontent.com/assets/3585151/19056986/984e4086-8981-11e6-86fe-d1ca45a7007d.png)

**Comment by mejackreed** [comment]
Can we have a `DELETE` route and have the service that does the delete hit that?

**Comment by mejackreed** [comment]
We also need to make sure to cleanup collections and release tags

**Comment by blalbrit** [comment]
@mejackreed - sorry to have missed the discussion of this in stand-up this morning. Is it the case that deleted objects will remain in the database, essentially overwriting the object row and removing a certain amount of information (targets, etc.)?

If so, and I'm sure you've already covered this, but when/if an object is republished (that is, when a deleted PURL gets re-created), does it then overwrite the object row again - adding the publish/release info back in - and removing the "delete date" (assuming that is a thing)? Was discussing with @LynnMcRae and was a little unclear on that particular set of points.

**Comment by mejackreed** [comment]
@blalbrit thanks for the follow up. I think we figured out all of the points we needed to this morning and your summary clears it right up.

Yes we keep the row in purl-fetcher, but mark it as dirty.
We also clean up the collections & release tags on it (6bdd403f6f7b079c19825a5d3574924c00239457)
If it does get recreated, then it _should_ update with the new collections and release tags.
