### ISSUE TITLE
ensure that all recent_changes files get processed on listener boot

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/purl-fetcher#185]
there's a race condition that when the listener is down, it'll miss (and leave) the notification files that were created during the downtime. the database recovers correctly via the delta find it spawns, _but_ the notification files do not get cleaned up.

**Comment by drh-stanford** [comment]
so I've dug deeper into this issue and it's not as straight-forward as I had hoped. The simple approach of adding a rake task to touch all the notification files must happen after the listener is started. There's some subtle problems (namely that the `start` task daemonized the process) trying to do that in the Rakefile as I had hoped. So, I'm still looking into a way that a simple `rake listener:restart` would work. Right now, the workaround requires 2 rake commands to accomplish a "reboot". Stay tuned...

**Comment by drh-stanford** [comment]
@eefahy I think the simplest approach is a cronjob that periodically touches all of the recent_changes files. When the listener is running, it'll pick them up immediately. If it's not running, then nothing will happen. I'll look into adding the `whenever` gem to purl-fetcher...

**Comment by eefahy** [comment]
OK, fair enough. Can you remind me where/when the file in `recent_changes` gets removed?

**Comment by drh-stanford** [comment]
The listener will sees that a new file shows up in `recent_changes`, it renames it from `druid` to `druid.lock`, then processes it, then deletes the `druid.lock` file. But, if the listener isn't running, then that `druid` touch file never gets noticed and will sit there forever (this happened after the reboot in early Sept).
