### ISSUE TITLE
PURL Fetcher collection call does not return members

### ISSUE THREAD

**Issue by lmcglohon** [sul-dlss/purl-fetcher#2]
PURL Fetcher is getting no results from a membership query for either collections

The correct field names are mostly correct in the solr_terms.yml in github
title_tsi
public_dc_title_t
id
true_releases_ssim
false_releases_ssim
identityMetadata_objectType_t
identityMetadata_objectType_tsim
is_member_of_collection_s
is_member_of_collection_ssim
indexed_dtsi

published_dt

version

timestamp

Purl fetcher does not support return an APO member query

**Comment by LynnMcRae** [comment]
PURL Fetcher would use different field names. Here's the list:

title_tsi
public_dc_title_t
id
true_releases_ssim
false_releases_ssim
identityMetadata_objectType_t
identityMetadata_objectType_tsim
is_member_of_collection_s
is_member_of_collection_ssim
indexed_dtsi                      
published_dt                      
_version_                        
timestamp        

Purl fetcher does not support return an APO member query

**Comment by drh-stanford** [comment]
- [ ] Need to restore the `/collections` API from #68
- [ ] Need to update the schema the retrieve collection metadata from correct field.
