### ISSUE TITLE
deprecate tmp/restart.txt?

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/purl-fetcher#24]
Should we be using `tmp/restart.txt` in the `AboutController`? I thought `cap env passenger:restart` was the preferred way to manage the server state...

**Comment by mejackreed** [comment]
I'm not really sure what this is really about? We allow users to hit an endpoint to restart the app?

**Comment by peetucket** [comment]
yeah, that was my code (also sued in previous projects), just information letting you know the last time code was deployed... each time this happens, capistrano touches restart.txt as part of the rails deploy process

if it is really a bad practice it can be safely removed
