### ISSUE TITLE
run a full reindex in stage

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/purl-fetcher#28]
From the filesystem (41,817 items) into the `purl-stage` solr code.

You can trigger a full reindex via `rake index_since_beginning_of_unix_time` (assuming this works)

Depends on https://github.com/sul-dlss/discovery-indexing/issues/15 and https://github.com/sul-dlss/discovery-indexing/issues/7 and https://github.com/sul-dlss/purl-fetcher/issues/22

- includes changes to the schema

**Comment by mejackreed** [comment]
If/when we deploy latest to stage, this should work. Verified yesterday on dev with `bundle exec rake full_reindex`

**Comment by drh-stanford** [comment]
See #99 -- stage has bad `public` XML data preventing a full run

**Comment by mejackreed** [comment]
This completed overnight, and seems successful. Though there is some duplicate information in the api response:

```json
{
  "druid": "druid:jp811tg1806",
  "latest_change": "2016-07-22T20:37:02Z",
  "true_targets": [
    "Searchworks",
    "Searchworks"
  ],
  "collections": [
    "druid:bs646cd8717",
    "druid:bs646cd8717"
  ]
}
```

**Comment by mejackreed** [comment]
Verified by @drh-stanford exemplar fixtures are appearing in API as expected.
