### ISSUE TITLE
Add catkey into purl index

### ISSUE THREAD

**Issue by lmcglohon** [sul-dlss/purl-fetcher#31]

**Comment by mejackreed** [comment]
What type of field should the catkey be given? Is there a preferred name?

**Comment by lmcglohon** [comment]
It should be a string and something with "catkey" in it would work as the field name

**Comment by mejackreed** [comment]
Gotcha thanks. Is this currently not working? https://github.com/sul-dlss/purl-fetcher/blob/master/lib/indexer.rb#L182-L187 I can investigate.

**Comment by LynnMcRae** [comment]
We are trying to follow the lead of the DOR index as a somewhat arbitrary but useful standard, e.g., https://argo.stanford.edu/catalog/druid:bb001mf4282.json.  That would make this field catkey_id_ssim.  What has brought this up as a need other than the general utility of finding PURLs by their catkey?

Note that DOR's solr doc has it expressed in several, rather redundant general ID fields -- identifier_ssim, identifier_tesim, dor_id_ssim, dor_id_tesim -- and oddly culled out as DC fields dc_identifier_catkey_ssi and dc_identifier_catkey_tesim.  Is there any interest in adding (just one of) these to index all identifiers in PURL.  The source would be identityMetadata/otherId and sourceId mapped into identifier_ssim or identifier_tesim.

**Comment by LynnMcRae** [comment]
Note PURL indexing specs at https://consul.stanford.edu/display/GRYPHONDOR/PURL+Indexing.  Are we still planning to convert to the field names in the DOR column?

**Comment by mejackreed** [comment]
Hm.. unless there is a different specification from what the ticket says, I think this is already working. Checkout:

```
https://solr-url.example.com/solr/purl-prod/select?indent=on&q=catkey_tsi:*&wt=json
```

We seem to have implemented as `catkey_tsi`.

**Comment by LynnMcRae** [comment]
The suffixes supposed mean something that reveal the characteristics of the solr field being managed, so as long as that is, uh, conforming? consistent? correct?  See https://github.com/projecthydra/hydra-head/wiki/Solr-Schema from our own Joe Atzberger.

**Comment by lmcglohon** [comment]
@mejackreed You are correct - it has been implemented - see https://sul-solr.stanford.edu/solr/purl-prod/select?indent=on&q=catkey_tsi:*&wt=json so I think we should close this ticket. @LynnMcRae ?
