### ISSUE TITLE
Improve (add) Logging

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/purl-fetcher#46]
* [x] log what druid & what action is being taken on the druid for indexer
* [x] log request & if request was fulfilled for fetcher --  who (external user vs dispatcher auto-mods), what (GET, parms), when, (most already in Apache log for incoming)
* [ ] request/response information viewable together, e.g., in squash or honeybadger equivalent)
* [x] consolidate log files

Existing:
* rails environment logging
* delete rake task log
* indexing rake task log

**Comment by drh-stanford** [comment]
The apache logs will have the who/what/when for the incoming requests so we don't need to log those in the application itself.

**Comment by drh-stanford** [comment]
I've spawned the final logging requirement into https://github.com/sul-dlss/purl-fetcher/issues/58 as I'm not clear on the actionable work for it.
