### ISSUE TITLE
Collection name from should come from MODS title data instead of identityMD objectLabel

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/purl-fetcher#466]
This is a related issue to sul-dlss/searchworks_traject_indexer#250 and [SW-4051](https://jirasul.stanford.edu/jira/browse/SW-4051). Collection names from PurlFetcher percolate down into Exhibits (e.g. for collection facets, among others).

Currently, it looks like PurlFetcher uses the publicXML's `identityMetadata/objectLabel` to fetch title of collection title; instead, we should be pulling from the MODS title of the collection object.

**Comment by jcoyne** [comment]
@anarchivist has this been fixed? I don't see where purl-fetcher is using objectLabel anywhere.

**Comment by anarchivist** [comment]
I believe this is fixed with our release of `mods_display` 1.0.
