### ISSUE TITLE
Populate collection membership database by reading from queue

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/purl-fetcher#563]
Once #562 is complete, we need to make sure that the database that powers the `/collections/:druid/purls` endpoint is updated based on up-to-date information from the queue. Exhibits uses this endpoint to figure what items to index when a curator wants to index an entire collection.

For an example of logic that reads from Kafka, see searchworks-traject-indexer's [`KafkaPurlFetcherReader`](https://github.com/sul-dlss/searchworks_traject_indexer/blob/master/lib/traject/readers/kafka_purl_fetcher_reader.rb) and note that our current kafka client is EOL (https://github.com/sul-dlss/searchworks_traject_indexer/issues/737).

**Comment by thatbudakguy** [comment]
Is this done? It looks to me like the `PurlCocinaUpdater` service dutifully updates the database records, including collection membership, when purls are updated.

**Comment by jcoyne** [comment]
I think it is
