### ISSUE TITLE
Remove unused endpoints

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/purl-fetcher#565]
#564 should allow us to remove GET from the `/purls` endpoint once all clients are consuming directly from kafka.

It seems possible that the `/purls/:druid` endpoint (fetch a single PURL by its druid) and `/collections` endpoint (fetch a list of all collections) are not used by any clients at the moment. If we can confirm this is true, we can remove them entirely.

**Comment by jcoyne** [comment]
I'm not seeing anything using the `/purls/*` (GET) or `/collections` endpoints. It looks like `/docs/deletes` and `/docs/changes` are where most of the interactions are.
