### ISSUE TITLE
provide request/response viewing in honeybadger

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/purl-fetcher#58]
From #46 we have a requirement to provide "request/response information viewable together, e.g., in squash or honeybadger equivalent)". I'm not sure exactly what this means. Do we have an example? It may be that Honeybadger already provides this functionality...

**Comment by LynnMcRae** [comment]
Apologies for any awkward wording.  There was mention of, say, the apache log would know about the incoming request and the app log would know what it did in response to a request. I just wanted to make sure that we could see that all the relevant parts of a transaction together, and made it easy to drill down on an error -- something squash does pretty well, to the extent the log has information about what is  being asked for/expected etc and then what went right or wrong. I'm also thinking of Web Service calls, where there's a clear PUT, POST etc interaction expressed as a URL and a clear http response.  Beyond a call for good logging, which Is superfluous I imagine, we can wait and see what the environment provides to support non-developer diagnostics (tying an error to a specific user/action/druid) and tweak from there as desired.

**Comment by lmcglohon** [comment]
@eefahy @LynnMcRae What is the status of this issue?

**Comment by LynnMcRae** [comment]
We need to see honey badger in action to tell if there's an issue.  When we took away showing the stack trace on error in Argo, squash provided equivalent access to the same diagnostic information readily online. We (e.g. Ben and me) need to make sure we continue to have that capability at a minimum without hunting it down in multiple logs.

**Comment by mejackreed** [comment]
Ping @LynnMcRae on this again. HoneyBadger is implemented and working properly as far as I can tell. The full stacktraces are available in HoneyBadger on exception. Can we close?

**Comment by blalbrit** [comment]
Honeybadger is not just good, it's good enough. Closing ticket.
