### ISSUE TITLE
Prototype Public XML generation from public Cocina

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/purl-fetcher#719]
If we have this, then we don't need to figure out a method to transfer an XML and a JSON file. Document any issues that would prevent us from moving this code from DSA.

See documenation on differences between public XML and public JSON: https://docs.google.com/document/d/1corbxySpzZMwIU4iKLPqY5j9xOAwEtBsMdDr2acMPl0/edit

Challenges
- [ ] #722 virtual objects. We query for parents that contain each object. This is written to descriptive metadata `relatedItem` - used by: Searchworks "Item is included in another record" see https://searchworks.stanford.edu/view/fn851zf9475 
- [ ] external resources  in ContentMetadataGenerator.
  - [ ] Exhibits uses this for the `tile_source` Solr field https://github.com/sul-dlss/exhibits/pull/2421
    - [ ] https://github.com/sul-dlss/exhibits/blob/cac6da0bf4a9b191c9fe3080180f19c30f2f4736/lib/traject/macros/dor.rb#L21
    - [ ] https://github.com/sul-dlss/exhibits/blob/cac6da0bf4a9b191c9fe3080180f19c30f2f4736/lib/traject/dor_config.rb#L210
  - [ ] Stacks - I'm not convinced Stacks is doing anything with external files: https://github.com/sul-dlss/stacks/pull/1141
    - [ ] https://github.com/sul-dlss/stacks/blob/72efc77f1354c33b6917632a698c173b634fdbdb/app/models/purl.rb#L61
  - [ ] purl - used for drawing IIIF manifests
    - [ ] https://github.com/sul-dlss/purl/blob/cd617ba055317985f4afdef85006815be0fedaff/app/services/resource_xml_deserializer.rb#L27-L28
  - [ ] indexing https://github.com/sul-dlss/searchworks_traject_indexer/pull/1439
    - [ ] https://github.com/sul-dlss/searchworks_traject_indexer/blob/9b1eb22eaaef3a39883da891584396e7bc264f70/lib/purl_record.rb#L154

**Comment by lwrubel** [comment]
Closing as completed.
