### ISSUE TITLE
Add local-metadata extension to OCFL in order to write unversioned metadata

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/purl-fetcher#756]
https://ocfl.io/1.1/spec/#documenting-local-extensions

Per dicussion on 05-23-2024 (https://docs.google.com/document/d/1juJ9xPuLtyiRBZzBd1xIh1UVslNL70akyHUNFQ7Nla4/edit) add a local-metadata extension to OCFL that will allow storage of unversioned metadata related to the object.

**Comment by mjgiarlo** [comment]
@jcoyne @justinlittman Are we calling the metadata local? Or is it a local extension for storage of unversioned metadata? If the latter, I wonder if should call this something like `unversioned-metadata` or `sidecar-metadata` instead of `local-metadata`.

**Comment by jcoyne** [comment]
@mjgiarlo any of those names is just fine by me.

**Comment by jcoyne** [comment]
I've decided to use @mjgiarlo's suggestion of "sidecar-metadata"
