### ISSUE TITLE
Add after save functionality for the purl index

### ISSUE THREAD

**Issue by lmcglohon** [sul-dlss/purl-fetcher#76]

**Comment by drh-stanford** [comment]
@eefahy and I were talking about indexing and for performance reasons (namely too many `RSolr.add` calls), we may want to use the `before_save` trigger (rather than `after_save`) so that we can leverage the `changed?` method, i.e.,

```ruby
before_save :save_solr
def save_solr(purl)
  solr.add(purl.to_solr) if purl.changed?
end
```

**Comment by drh-stanford** [comment]
fyi I had some more ideas about the implementation design of this if we proceed

**Comment by eefahy** [comment]
Can we schedule a team discussion on the best way forward with this ticket in light of where the code is right now?

**Comment by drh-stanford** [comment]
fine by me. do you want to schedule it?

**Comment by drh-stanford** [comment]
I'm blocked pending a discussion with the team. So this issue is on hold right now...
