### ISSUE TITLE
publish step does not remove .deletes file on republish

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/purl-fetcher#90]
On republish (after being withdrawn), the Dor::Item.publish_metadata step does not remove the druid file from the `.deletes` directory.

So the `/purl/document_cache` can get into an inconsistent state where if a PURL is published, then withdrawn, then published, you'll have both a `public` and `.deleted` file.

**Comment by drh-stanford** [comment]
All of the `.deletes` code is buried inside DruidTools, not dor-services. See https://github.com/sul-dlss/druid-tools/blob/master/lib/druid_tools/druid.rb

**Comment by peetucket** [comment]
So...the scenario is:

1. release=true, publish a document, get a public xml entry
2. release=false, then publish, get a .deletes entry (public xml remains)
3. release=true, then publish <-- this should remove the .deletes entry but currently does not?

Isn't having a .deletes and a public XML file an acceptable state?  The .deletes is referring to it not being indexed anymore, not necessarily that it was moved from purl?

I did notice that we may want to create a .deletes entry in the case that an item has its rights changed to non-world discoverable (e.g. dark) -- i.e. imply an immediate release=false in this case.  It could happen here:

https://github.com/sul-dlss/dor-services/blob/cd2bb745bc042f90b1967828652fdff5425ab058/lib/dor/models/publishable.rb#L67

**Comment by LynnMcRae** [comment]
.deletes is tied solely to the non-existence of the Purl and has nothing to do with release status. It is only recorded when publish is taking the public XML files away. If a purl exists, it is indexed along with the current release information true and false.

If the rights are changed to dark (\<access type="discover"> becomes \<"/none"), then the Purl is withdrawn -- the content files are deleted from the Digital Stacks by the shelve robot, public XML files are deleted from the document cache by publish, and the disappearance of the Purl is recorded in .deletes.  If the Purl comes back, the .deletes entry needs to go away.

**Comment by peetucket** [comment]
OK, so I think we just need to call the ".deletes_delete_record" method of this object in DruidTools: 

https://github.com/sul-dlss/druid-tools/blob/master/lib/druid_tools/druid.rb

on each publish_metadata call that results in the creation of a public XML file (e.g. in the method called "publish_notify_on_success" here: 

https://github.com/sul-dlss/dor-services/blob/master/lib/dor/models/publishable.rb#L84)

**Comment by peetucket** [comment]
PR ready: https://github.com/sul-dlss/dor-services/pull/228

**Comment by jmartin-sul** [comment]
PR for argo update here:  https://github.com/sul-dlss/argo/pull/798

once that's merged, should be quick to tag a new release and deploy it.

**Comment by drh-stanford** [comment]
@peetucket is it ok for me to deploy `common-accessioning` to production now?

**Comment by peetucket** [comment]
Go for it.

**Comment by drh-stanford** [comment]
the latest common-accessioning is now in production

**Comment by drh-stanford** [comment]
I have a PR for `dor-services-app` to upgrade -- see https://github.com/sul-dlss/dor-services-app/pull/29

**Comment by drh-stanford** [comment]
The `dor-services-app` deploy to production is blocked on SAR-3243

**Comment by drh-stanford** [comment]
dor-services-app is deployed in production now
