### ISSUE TITLE
VersionFileService.delete should delete all files

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/purl-fetcher#906]
This includes all files for the object in stacks and purl.

**Comment by aaron-collier** [comment]
I wonder if we should just remove the version param from https://github.com/sul-dlss/purl-fetcher/blob/main/app/controllers/v1/purls_controller.rb#L36 and/or remove the versioned files branch here: https://github.com/sul-dlss/purl-fetcher/blob/main/app/services/purl_and_stacks_service.rb#L48

**Comment by justinlittman** [comment]
Agree with removing the version param.

While getting rid of the versioned file branch might have the desired effect, once we get rid of the non-versioned code the remaining code will be a bit messy so I'd recommend implementing the delete within the VersionFileService. This will allow us to more easily get rid of the PurlAndStackService abstraction layer.
