### ISSUE TITLE
Modify collections endpoint to accomodate `collection|set` object_type

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/purl-fetcher#96]
or change `PurlParser` to not join multiple type?

```sh
> Purl.uniq.pluck(:object_type)
 => ["item", "collection", "collection|set"]
```

**Comment by drh-stanford** [comment]
This looks like bad data to me -- I would think `PurlParser` should thrown an exception if there are 2 object types for a single Purl. Is this spec'd somewhere or can we get clarification?

**Comment by LynnMcRae** [comment]
While there are often paired RELS-EXT relationships for isMemberOf (generic aggregation, i.e. set) and isMemberOfCollection (what kind of aggregation), there should indeed be only one object-type. We'll clean up some, but observe that Hydrus seems to be producing objects with this dual object type, so we may have to accommodate that dual object-type scenario until Hydrus can be fixed (which I assume is not soon).
